/// MiasmaFFI.swift — UniFFI-generated Swift bindings stub.
///
/// THIS FILE IS AUTO-GENERATED by uniffi-bindgen.
/// Run to regenerate:
///   uniffi-bindgen generate \
///       --library ../../../target/aarch64-apple-ios/release/libmiasma_ffi.a \
///       --language swift \
///       --out-dir ios/MiasmaApp/Sources/MiasmaFFI/
///
/// The stub below exists only for IDE navigation during development without
/// the Rust toolchain. It is replaced by the generated file during a real build.

import Foundation

// MARK: - Records

public struct NodeStatusFfi {
    public let shareCount: UInt64
    public let usedMb: Double
    public let quotaMb: UInt64
    public let listenAddr: String
    public let bootstrapCount: UInt64
}

public struct EmbeddedDaemonStatus {
    public let httpPort: UInt16
    public let peerId: String
    public let sharingContact: String
}

public struct EnvelopeSummaryFfi {
    public let id: String
    public let senderKey: String
    public let state: String
    public let challengeCode: String?
    public let createdAt: UInt64
    public let expiresAt: UInt64
}

// MARK: - Errors

public enum MiasmaFfiError: Error {
    case notInitialized(dataDir: String)
    case invalidMid(reason: String)
    case insufficientShares(need: UInt64, got: UInt64)
    case inputTooLarge(size: UInt64, max: UInt64)
    case other(msg: String)
}

// MARK: - Core functions (stubs)

public func initializeNode(dataDir: String, storageMb: UInt64, bandwidthMbDay: UInt64) throws {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded — run cargo build + uniffi-bindgen")
}

public func dissolveBytes(dataDir: String, data: Data) throws -> String {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func retrieveBytes(dataDir: String, midStr: String) throws -> Data {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func getNodeStatus(dataDir: String) throws -> NodeStatusFfi {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func distressWipe(dataDir: String) throws {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

// MARK: - Embedded daemon functions (stubs)

public func startEmbeddedDaemon(dataDir: String, storageMb: UInt64, bandwidthMbDay: UInt64) throws -> EmbeddedDaemonStatus {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func stopEmbeddedDaemon() {
    // No-op in stub
}

public func getDaemonHttpPort() -> UInt16 {
    return 0
}

public func isDaemonRunning() -> Bool {
    return false
}

public func getSharingContact() -> String {
    return ""
}

// MARK: - Directed sharing functions (stubs)

public func getSharingKey(dataDir: String) throws -> String {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func listDirectedInbox(dataDir: String) throws -> [EnvelopeSummaryFfi] {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func listDirectedOutbox(dataDir: String) throws -> [EnvelopeSummaryFfi] {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func deleteDirectedEnvelope(dataDir: String, envelopeId: String) throws {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}
