/// MiasmaFFI.swift — UniFFI-generated Swift bindings stub.
///
/// THIS FILE IS AUTO-GENERATED by uniffi-bindgen.
/// Run to regenerate:
///   uniffi-bindgen generate \
///       --library ../../../target/aarch64-apple-ios/release/libmiasma_ffi.a \
///       --language swift \
///       --out-dir ios/MiasmaApp/Sources/MiasmaFFI/
///
/// The stub below exists only for IDE navigation during development without
/// the Rust toolchain. It is replaced by the generated file during a real build.

import Foundation

// MARK: - Records

public struct NodeStatusFfi {
    public let shareCount: UInt64
    public let usedMb: Double
    public let quotaMb: UInt64
    public let listenAddr: String
    public let bootstrapCount: UInt64
}

// MARK: - Errors

public enum MiasmaFfiError: Error {
    case notInitialized(dataDir: String)
    case invalidMid(reason: String)
    case insufficientShares(need: UInt64, got: UInt64)
    case other(msg: String)
}

// MARK: - Functions (stubs)

public func initializeNode(dataDir: String, storageMb: UInt64, bandwidthMbDay: UInt64) throws {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded — run cargo build + uniffi-bindgen")
}

public func dissolveBytes(dataDir: String, data: Data) throws -> String {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func retrieveBytes(dataDir: String, midStr: String) throws -> Data {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func getNodeStatus(dataDir: String) throws -> NodeStatusFfi {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}

public func distressWipe(dataDir: String) throws {
    throw MiasmaFfiError.other(msg: "Generated FFI not loaded")
}
