// THIS FILE IS AUTO-GENERATED by uniffi-bindgen.
//
// Run to regenerate:
//   uniffi-bindgen generate \
//       --library ../../../../target/debug/libmiasma_ffi.so \
//       --language kotlin \
//       --out-dir android/app/src/main/kotlin/dev/miasma/uniffi/
//
// The stub below is only for IDE navigation / compilation gating during development
// without the NDK. It is replaced by the generated file during a real build.

package dev.miasma.uniffi

// ──── Records ────────────────────────────────────────────────────────────────

data class NodeStatusFfi(
    val shareCount: Long,
    val usedMb: Double,
    val quotaMb: Long,
    val listenAddr: String,
    val bootstrapCount: Long,
)

// ──── Errors ─────────────────────────────────────────────────────────────────

sealed class MiasmaFfiException(message: String) : Exception(message) {
    class NotInitialized(val dataDir: String) :
        MiasmaFfiException("Node not initialised at '$dataDir'. Call initialize_node first.")

    class InvalidMid(val reason: String) :
        MiasmaFfiException("Invalid MID: $reason")

    class InsufficientShares(val need: Long, val got: Long) :
        MiasmaFfiException("Insufficient shares: need $need, found $got")

    class Other(val msg: String) :
        MiasmaFfiException(msg)
}

// ──── FFI stubs (replaced by generated code at build time) ───────────────────
//
// In a production build these are NOT present — uniffi-bindgen emits the real
// JNI-backed implementations.  The stubs throw UnsupportedOperationException so
// that unit tests that mock the layer can still compile cleanly.

@Throws(MiasmaFfiException::class)
fun initializeNode(dataDir: String, storageMb: Long, bandwidthMbDay: Long): Unit =
    throw UnsupportedOperationException("Generated FFI not loaded — run cargo ndk + uniffi-bindgen")

@Throws(MiasmaFfiException::class)
fun dissolveBytes(dataDir: String, data: ByteArray): String =
    throw UnsupportedOperationException("Generated FFI not loaded")

@Throws(MiasmaFfiException::class)
fun retrieveBytes(dataDir: String, midStr: String): ByteArray =
    throw UnsupportedOperationException("Generated FFI not loaded")

@Throws(MiasmaFfiException::class)
fun getNodeStatus(dataDir: String): NodeStatusFfi =
    throw UnsupportedOperationException("Generated FFI not loaded")

@Throws(MiasmaFfiException::class)
fun distressWipe(dataDir: String): Unit =
    throw UnsupportedOperationException("Generated FFI not loaded")
