# UniFFI — keep all JNI entry points generated by uniffi-bindgen.
-keep class dev.miasma.uniffi.** { *; }
-keepclasseswithmembernames class * {
    native <methods>;
}

# ZXing / BarcodeScanner
-keep class com.google.zxing.** { *; }
-keep class com.journeyapps.** { *; }

# Kotlin coroutines
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
